[tool.poetry]
name = "remotestick-server"
version = "0.0.1"
authors = [ ]
description = "Web ui for tellstick"
exclude = [".idea"]


[tool.poetry.dependencies]
python = "^3.6"
bottle = "^0.12.23"

[tool.poetry.scripts]
run = "remotestick_server.server:main"
